CC = g++
CFLAGS = -std=c++20 -Wall

.PHONY: all clean

all: part1 part2

part1: part1.cpp
	$(CC) $(CFLAGS) -o part1 part1.cpp

part2: part2.cpp
	$(CC) $(CFLAGS) -o part2 part2.cpp

clean:
	rm -f part1 part2
